---
language: node_js

sudo: false

cache:
  directories:
    - node_modules

before_install:
  - "export CHROME_BIN=`which chromium-browser`"
  - "npm config set spin false"
  - "npm install -g npm@^2"

install:
  - npm install

script:
  - make tests